# Change these first
owner: wont-stream # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Website IPv6
    url: https://ipv4.army
    ipv6: true
  - name: Website IPv4
    url: https://ipv4.army
    ipv6: true

assignees: # Users to assign downtime issues (optional)
  - wont-stream
skipDeleteIssues: true

status-website:
  cname: uptime.ipv4.army
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime
  js: "fetch('https://1.ipv4.army/api/event',{method:'POST',body:JSON.stringify({domain:'uptime.ipv4.army',name:'pageview',url:location.href,referrer:document.referrer,props:{languages:navigator.languages.join(', ')}})});"

workflowSchedule:
  graphs: "* * * * *"
  responseTime: "* * * * *"
  staticSite: "* * * * *"
  summary: "* * * * *"
  updateTemplate: "* * * * *"
  updates: "* * * * *"
  uptime: "* * * * *"

user-agent: wont-stream
